# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 821048c19f5d7d54bf9fa193f5b6f46ed1c7c8149a31a09e2b762a4403e4c5f8ede9118b3c66e823d54741f48dc2e11547ab5624e31d2628afb78d50c05f1582

test:
  secret_key_base: 8902a78550798325e5b78714e40b5f0a6de719ec4fbb561c62ddd081a0d416b6a7b4bf74b564ffd1b0ba3385b5d09addf3e49e96c5602e994a5065e1dcaf245f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
